version: "3.8"
services:
  dev-db:
    image: postgres:13
    container_name: dev-db
    ports:
      - "5555:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - dev-network
networks:
  dev-network:
